
name: Tests

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  not_slow:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: True
      matrix:
        python-version: [3.8, "3.11.8"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: |
        python -m pip install nox_poetry
    - name: Test with nox
      run: nox -s tests -- -m "not slow"
